- name: Install apt packages for GPG and NGINX
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - gnupg-agent
      - nginx
      - software-properties-common
    state: present
- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
- name: "Add nodejs 14.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x focal main
    update_cache: yes
- name: Install apt packages for nodejs
  apt:
    update_cache: yes
    name:
      - nodejs
    state: present
- name: Install globally npm package "pm2"
  npm:
    name: pm2
    global: yes
    state: present