- name: Install apt packages for PHP
  apt:
    update_cache: yes
    name:
      - php-fpm
      - php-curl
      - php-mysql
      - curl
      - git
      - gnupg-agent
      - nginx
    state: present
- name: ensure php5-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php/7.4/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify:
    - restart php-fpm
    - restart nginx
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer